add rubocop
ronin-rb/ronin-web-browser pull request #3
Opened 2023-02-23 16:43 UTC by evpgh

- Add rubocop
- Add rubocop to CI

2023-02-23 17:25 UTC, postmodern commented
I think you forgot to copy in the full `.rubocop.yml` file from `ronin-template`. A lot of the rules in it disable [various pedantic rubocop rules](https://github.com/ronin-rb/ronin-template/blob/main/.rubocop.yml#L88-L155). I can also review the disabled rules and ensure that they should be left disabled.

2023-02-23 17:33 UTC, postmodern requested changes
Missing the other disabled rubocop rules from the [`.rubocop.yml` template](https://github.com/ronin-rb/ronin-template/blob/b107a4b0e0e6e7836c88f4cd26d1522e90c8d989/.rubocop.yml#L88-L155), which should eliminate most of the small changes.

2023-02-23 17:33 UTC, postmodern commented on .rubocop.yml
> +    - 'ronin-web-template.gemspec'
`ronin-web-template` -> `ronin-web-browser`.

2023-02-23 17:33 UTC, postmodern commented on Gemfile
> +  gem 'redcarpet', platform: :mri
I'm actually a fan of vertical alignment. It makes it easier to edit the version requirements.

2023-02-23 17:33 UTC, postmodern commented on Rakefile
> +Gem::Tasks.new(sign: { checksum: true, pgp: true })
Is `rubocop` adding those spaces?

2023-02-23 17:33 UTC, postmodern commented on lib/ronin/web/browser/agent.rb
>                        password: proxy.password
Again, I prefer vertical alignment.

2023-02-23 17:33 UTC, postmodern commented on lib/ronin/web/browser/agent.rb
> +                    raise(ArgumentError, "invalid proxy value (#{proxy.inspect}), must be either a Hash, URI::HTTP, String, or nil")
I tend to omit the spaces in method calls. It saves time and doesn't impact readability that much (I think).

2023-02-23 17:33 UTC, postmodern commented on lib/ronin/web/browser.rb
> +        Agent.open(**kwargs, &block)
It's OK to omit spaces between arguments here.

2023-02-23 17:33 UTC, postmodern commented on lib/ronin/web/browser/agent.rb
> +            super('Network.responseReceived') do |params, index, total|
Not a fan of spaces in block arguments.

2023-02-23 17:33 UTC, postmodern commented on ronin-web-browser.gemspec
> +    gem.add_development_dependency(name, split[versions])
I would just ignore the `.gemspec` file. It's a boilerplate file that can be updated later by coping in a new version.

2023-02-23 17:33 UTC, postmodern commented on spec/agent_spec.rb
> +    context 'when Ronin::Support::Network::HTTP.proxy is set' do
For some reason I always use double quoted strings in RSpec tests. Old habits die hard I guess.

2023-02-23 17:33 UTC, postmodern commented on spec/browser_spec.rb
> +        end.to yield_successive_args(described_class::Agent)
I **strongly** disagree with this rubocop rule. When chaining together multiple methods that take a block, curly brace blocks are the defacto standard. I really have no clue how that rule got into rubocop in the first place, and wish they would remove it.

2023-02-23 17:33 UTC, postmodern commented on .rubocop.yml
> +
Missing the other disabled rules from the [`.rubocop.yml` template](https://github.com/ronin-rb/ronin-template/blob/b107a4b0e0e6e7836c88f4cd26d1522e90c8d989/.rubocop.yml#L88-L155).

2023-02-23 17:33 UTC, postmodern commented on lib/ronin/web/browser/agent.rb
> +          browser
I'm a fan of sometimes using explicit `return`s. I feel it's weird to have a local variable just sitting there on the last line. I know, it's a weird habit that I developed after years of writing C/C++/Java...

2023-02-24 08:20 UTC, evpgh commented
I'll just close this PR and create a new one.

2023-02-24 08:20 UTC, closed without merging

2023-02-24 23:59 UTC, postmodern commented
Let me create the `rubocop-ronin` gem to contain the new common rubocop rules and update the template `.rubocop.yml` to use that.

2023-02-25 01:30 UTC, postmodern commented
Done. See https://github.com/ronin-rb/rubocop-ronin#readme and the new [`.rubocop.yml` template file](https://github.com/ronin-rb/ronin-template/blob/main/.rubocop.yml).